### ISSUE TITLE
error: no viable conversion from 'std::atomic<int>' to 'const UniValue'

### ISSUE THREAD

**Issue by luke-jr** [jgarzik/univalue#76]
Regression introduced by PR #61

With GCC 9.3.0, building Bitcoin Core 0.17+:

```
rpc/blockchain.cpp:2077:35: error: no viable conversion from 'std::atomic<int>' to 'const UniValue'
        result.pushKV("progress", g_scan_progress);
                                  ^~~~~~~~~~~~~~~
```

**Comment by luke-jr** [comment]
@promag

**Comment by promag** [comment]
You think it should be reverted or that code should change to `g_scan_progress.load()`?

**Comment by luke-jr** [comment]
If the API is going to change, it should wait for 2.0 I guess

**Comment by luke-jr** [comment]
(It does seem cleaner to simply allow it implicitly, though)
